name: Add Community

on:
  issues:
    types: [opened]

jobs:
  process-community:
    if: contains(github.event.issue.labels.*.name, 'add-community')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse issue form
        id: issue-parser
        uses: stefanbuck/github-issue-parser@v3
        with:
          template-path: .github/ISSUE_TEMPLATE/01-add-community.yml

      - name: Validate and process community
        id: process
        uses: actions/github-script@v7
        env:
          PARSED_ISSUE: ${{ steps.issue-parser.outputs.jsonString }}
        with:
          script: |
            const script = require('./.github/scripts/parse-community.js');
            await script({ github, context, core, process })();

      - name: Check if community already exists
        if: steps.process.outputs.valid == 'true'
        id: check_exists
        run: |
          if [ -f "src/content/communities/${{ steps.process.outputs.slug }}.yaml" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Comment if community exists
        if: steps.process.outputs.valid == 'true' && steps.check_exists.outputs.exists == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `❌ **Comunidade xa existe**\n\nXa existe unha comunidade co slug \`${{ steps.process.outputs.slug }}\`. Por favor verifica se xa está rexistrada ou cambia o nome.`
            });
            
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['duplicate']
            });

      - name: Create branch and file
        if: steps.process.outputs.valid == 'true' && steps.check_exists.outputs.exists == 'false'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create branch
          BRANCH="add-community-${{ steps.process.outputs.slug }}"
          git checkout -b "$BRANCH"
          
          # Create community file
          echo "${{ steps.process.outputs.yaml_content }}" > "src/content/communities/${{ steps.process.outputs.slug }}.yaml"
          
          # Commit changes
          git add "src/content/communities/${{ steps.process.outputs.slug }}.yaml"
          git commit -m "feat: engade comunidade ${{ steps.process.outputs.name }}

          - Engade nova comunidade: ${{ steps.process.outputs.name }}
          - Ficheiro: src/content/communities/${{ steps.process.outputs.slug }}.yaml
          - Closes #${{ github.event.issue.number }}"
          
          # Push branch
          git push origin "$BRANCH"
          
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request
        if: steps.process.outputs.valid == 'true' && steps.check_exists.outputs.exists == 'false'
        uses: actions/github-script@v7
        env:
          NAME: ${{ steps.process.outputs.name }}
          SLUG: ${{ steps.process.outputs.slug }}
        with:
          script: |
            const script = require('./.github/scripts/create-pr.js');
            await script({ github, context, core })('community', {
              name: process.env.NAME,
              slug: process.env.SLUG
            });