name: Add Event

on:
  issues:
    types: [opened, edited, labeled, reopened]

jobs:
  process-event:
    if: contains(github.event.issue.labels.*.name, 'add-event')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse issue form
        id: issue-parser
        uses: stefanbuck/github-issue-parser@v3
        with:
          template-path: .github/ISSUE_TEMPLATE/02-add-event.yml

      - name: Validate and process event
        id: process
        uses: actions/github-script@v6
        env:
          PARSED_ISSUE: ${{ steps.issue-parser.outputs.jsonString }}
        with:
          script: |
            const script = require('./.github/scripts/parse-event.js')
            await script({github, context, core})
